version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - solport-data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URI=sqlite:////app/data/portfolio.db
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/solport
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/solport:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - backend
    restart: unless-stopped

volumes:
  solport-data:
  redis-data:
